import { User } from './users.model'
import { IUser } from './users.interface'
import config from '../../../config/index'
import { generatedUserId } from './users.utils'
//database logic
const createUser = async (user: IUser): Promise<IUser | null> => {
  // autogenerated incremental id
  const id = await generatedUserId()
  user.id = id
  //default password
  if (!user.password) {
    //!user.password mane tmi jodi passwordfield na dao tahole
    user.password = config.default_user_pass as string
    //ami default password use korbo.
  }
  const createdUser = await User.create(user)
  if (!createUser) {
    throw new Error('Failed to create user!')
  }
  return createdUser
}
export default {
  createUser,
}
